{
    'name': 'Gelato Theme',
    'category': 'Theme/Food',
    'version': '18.0.1.1.0',
    'summary': 'Gelato, Ice Cream, Restaurant, Cafe, Food, Catering',
    'description': 'Full website theme for Gelato! Karlovy Vary, Italian gelato shop.',
    'author': 'VaryShop',
    'license': 'LGPL-3',
    'sequence': 900,
    'depends': [
        'theme_common',
        'website',
        'mail',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/generate_primary_template.xml',
        'data/ir_asset.xml',
        'views/gelato_hero_slide_views.xml',
        'views/gelato_gallery_image_views.xml',
        'views/layout.xml',
        'views/snippets/s_gelato_hero.xml',
        'views/snippets/s_gelato_why.xml',
        'views/snippets/s_gelato_gallery.xml',
        'views/snippets/s_gelato_reviews.xml',
        'views/snippets/s_gelato_location.xml',
        'views/snippets/s_gelato_map.xml',
        'views/snippets/s_gelato_inquiry.xml',
        'views/snippets/s_gelato_cta.xml',
        'views/snippets/snippets_registry.xml',
        'views/pages.xml',
        'data/website_menu_data.xml',
        'data/gelato_hero_slide_data.xml',
        'data/gelato_gallery_image_data.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'theme_gelato/static/src/js/main.js',
        ],
    },
    'images': [
        'static/description/theme_screenshot.png',
    ],
    'installable': True,
    'application': False,
}
